
  spring:
    security:
      oauth2:
        client:
          registration:
            google:
              clientId: 884863571244-2vscq8q92sj4ar6t44n4sqru8sschun3.apps.googleusercontent.com
              clientSecret: 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

  twilio:
    account_sid: AC8f7c763c17c52a3092a54ce299689286
    auth_token: 313e19a22bef5ab13af5bdb93273c739
    trial_number: +15674092533
