spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 884863571244-2vscq8q92sj4ar6t44n4sqru8sschun3.apps.googleusercontent.com
            client-secret: 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